CC=gcc
CFLAGS=-I.

echoserver: echoserver.c readline.c readn.c writen.c
	$(CC) -o echoserver echoserver.c readline.c readn.c writen.c $(CFLAGS)
tcpcli: tcpcli01.c readline.c readn.c writen.c
	$(CC) -o tcpcli tcpcli01.c readline.c readn.c writen.c $(CFLAGS)
